app1/urls.py
from django.urls import include, path
from app1.views import add_to_cart, add_to_wishlist, ajax_add_review, cart_view, checkout_view, customer_dashboard, delete_item_from_cart,filter_product, index, category_product_list_view, make_address_default, order_detail, payment_completed_view, payment_failed_view, profile_update, remove_wishlist, search_view,tag_list, product_detail_view, update_cart, vendor_detail_view, vendor_list_view, wishlist_view
#from django.conf import settings
#from django.conf.urls.static import static
#from django.contrib import admin

app_name = "app1"

urlpatterns = [
  path('', index),

  path('item/<pid>',product_detail_view,name='product-detail'),

  path('category/<cid>/',category_product_list_view,name='catlist'),
  path('vendors/',vendor_list_view,name='vendor-list'),
  path('vendor/<vid>',vendor_detail_view,name='vendor-detail'),
  path("products/tag/<slug:tag_slug>/", tag_list, name="tags"),
  path('search/',search_view,name='search'),
  path('ajax-add-view/<int:pid>/',ajax_add_review,name='ajax-add-view'),

  path('filter-products/',filter_product,name='filter-product'),
    
  path('add-to-cart/',add_to_cart,name='add-to-cart'),
  
  path('cart/',cart_view,name='cart'),
  path('delete-from-cart/',delete_item_from_cart,name='delete-from-cart'),
  path('update-cart/',update_cart,name='update-cart'),

  path('checkout/',checkout_view,name='checkout'),
  
  path('paypal/',include('paypal.standard.ipn.urls')),

    
  path('payment-completed/',payment_completed_view,name='payment-completed'),
  path('payment-failed/',payment_failed_view,name='payment-failed'),
  path('dashboard/',customer_dashboard,name='dashboard'),

  path('dashboard/order/<int:id>',order_detail,name='order-detail'),

  path('make-default-address/',  make_address_default ,name='make-default-address'),
  
  path('wishlist/',  wishlist_view ,name='wishlist'),

  path('add-to-wishlist/',  add_to_wishlist ,name='add-to-wishlist'),
  
  path('remove-from-wishlist/',  remove_wishlist ,name='remove-from-wishlist'),

  path('profile/update/', profile_update ,name='profile-update'),





















    # ... other URL patterns here
]

'''if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) '''

cafeteria/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views
from django.conf import settings
from django.conf.urls.static import static

'''if we make url.py in the app
   then we dont need to write path('',views.SignupPage,name='signup')
   we can simply use from .views import * 
   and write path('',SignupPage,name='signup'),
'''
urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("app1.urls")),
    #path('',views.SignupPage,name='signup'),
    path('',views.index),
    path('login/',views.LoginPage,name='login'),
    path('signup/',views.SignupPage,name='signup'),
    path('logout/',views.LogoutPage,name='logout'),
    
    path('index/',views.index, name='index'),
    path('items/',views.items,name='items'),
    path('popular/',views.popular,name='popular'),
    path('category/',views.categorylist,name='category'),



    path('home/',views.HomePage,name='home'),
    path('token/',views.token_send,name='token_send'),
    path('success/',views.success,name='success'),
    path('verify/<auth_token>' , views.verify , name="verify"),
    path('error' , views.error_page , name="error"),

    path("ckeditor/",include("ckeditor_uploader.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/async/cart-list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Cart | NSU Cafeteria</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        
        
        <!-- Cart Start -->
        <div class="cart-page" id="cart-list">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8">
                        <div style="color: green; font-weight: bold;">
                            <p>
                            There are <span style="color: #FF6F61;">{{totalcartitems}}</span> items for you 
                            </p>
                        </div>

                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Product</th>
                                            <th>Unit price</th>
                                            <th>Quantity</th>
                                            <th>Total</th>
                                            <th>Refresh</th>

                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">

                                        {% for product_id, item in cart_data.items %}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href="{% url 'app1:product-detail' item.pid %}"><img src="{{ item.image }}" alt="Image"></a>
                                                    <a href="{% url 'app1:product-detail' item.pid %}">
                                                        <p> {{ item.title }} </p>
                                                    </a>
                                                </div>
                                            </td>
                                            <td> {{ item.price|floatformat:1 }}/- </td>
                                            <td>
                                                <div class="qty">
                                                    <button class="btn-minus"><i class="fa fa-minus"></i></button>

                                                    <input type="text" value="{{ item.qty }}" id="" class="product-qty-{{product_id}}">
                                                    <button class="btn-plus"><i class="fa fa-plus"></i></button>
                                                </div>
                                            </td>
                                            <td> 
                                                <h5> {%  widthratio item.price 1 item.qty %}/- </h5>
                                            </td>
                                            <td><button class="update-product" data-product="{{ product_id }}"><i class="fa fa-recycle"></i></button></td>
                                            <td><button class="delete-product" data-product="{{ product_id }}"><i class="fa fa-trash" ></i></button></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="cart-page-inner">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="coupon">
                                        <input type="text" placeholder="Coupon Code">
                                        <button>Apply Code</button>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="cart-summary">
                                        <div class="cart-content">
                                            <h1>Cart Summary</h1>
                                            <p>Sub Total<span> {{ cart_total_amount|floatformat:2 }}/- </span></p>
                                            <p>Shipping Cost<span>10/-</span></p>
                                            <h2>Grand Total<span> {{ gta|floatformat:2 }}Tk </span></h2>
                                        </div>
                                        <div class="cart-btn">
                                            <a href="{% url 'items' %}"><button class="">
                                                <span class="icon"><i class="fas fa-plus"></i>
                                                </span> Add more Items                                    
                                            </button></a>
                                            {% if totalcartitems %}                                          
                                            <a href="{% url 'app1:checkout' %}"><button class="">
                                                <span class="icon">🛒</span> Checkout                                         
                                            </button></a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Cart End -->
        
        
        
        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>
        
        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/function.js' %}"></script>

    </body>
</html>

templates/async/product-list.html
{% for p in products %}
                                <div class="col-md-4">
                                    <div class="product-item">
                                        <div class="hot-label">
                                            {% if p.get_percentage|floatformat:0|add:0 > 0 %}
                                                +{{ p.get_percentage | floatformat:0}}%
                                            {% else %}
                                                {{ p.get_percentage | floatformat:0 }}%
                                            {% endif %}
                                        </div>
                                                                            
                                        <div class="product-title">
                                            <p style="color: white;">{{ p.category.title }}</p>
                                            <a href="#"> {{ p.title }} </a>
                                            <div class="ratting">
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                                <i class="fa fa-star"></i>
                                            </div>
                                        </div>

                                        <div class="product-image">
                                            <a href="product-detail.html">
                                                <img src="{{ p.image.url }}" alt="Product Image">
                                            </a>
                                            <div class="product-action">
                                                
                                                <a href="{% url 'app1:cart' %}"><i class="fa fa-cart-plus"></i></a>
                                                <a href="#"><i class="fa fa-heart"></i></a>
                                                <a href="{% url 'app1:product-detail' p.pid %}"><i class="fa fa-search"></i></a>
                                            </div>
                                        </div>
                                        
                                        <div class="product-price">
                                            <h3 class="current-product-price-{{p.id}}"> {{ p.price }} </h3>
                                            <span style="color: white;">/-</span>
                                            <p class="pross"> {{ p.old_price }} <span>/-</span></p>

                                            <input type="hidden" value="1" name="" id="product-quantity" class="product-quantity-{{p.id}}" >
                                            <input type="hidden" value="{{p.pid}}" name="" id="" class="product-pid-{{p.id}}" >
                                            <input type="hidden" value="{{p.image.url}}" id="" class="product-image-{{p.id}}" >
                                            <input type="hidden" value="{{p.id}}" id="" class="product-id-{{p.id}}" >
                                            <input type="hidden" value="{{p.title}}" name="" id="" class="product-title-{{p.id}}" >


                                            <button class="btn add-to-cart-btn" data-index="{{p.id}}" id="add-to-cart-btn"><i class="fa fa-shopping-cart"></i>Buy Now</button>                          
                                            <p style="color: #FF6F61;">By: {{ p.vendor.title }}</p>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}

templates/async/wishlist-list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Cart | NSU Cafeteria</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="eCommerce HTML Template Free Download" name="keywords">
        <meta content="eCommerce HTML Template Free Download" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Source+Code+Pro:700,900&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>


    <body>
        
        <!-- Wishlist Start -->
        <div class="wishlist-page" id="wishlist-list">
            <div class="container-fluid">
                <div class="wishlist-page-inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div style="color: green; font-weight: bold;">
                                <p>
                                There are <span style="color: #FF6F61;">{{wishlist.count}}</span> items for youu 
                                </p>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Stock</th>
                                            <th>Add to Cart</th>
                                            <th>Remove</th>
                                        </tr>
                                    </thead>
                                    <tbody class="align-middle">
                                        {% for w in w %}
                                        <tr>
                                            <td>
                                                <div class="img">
                                                    <a href=" {% url 'app1:product-detail' w.product.pid%} "><img src="{{w.product.image.url}}" alt="Image"></a>
                                                    <a href=" {% url 'app1:product-detail' w.product.pid%} "><p>{{ w.product.title|truncatechars:30 }}</p> </a>
                                                </div>
                                            </td>
                                            <td> <span class="current-product-price-{{w.product.id}}">{{w.product.price}} </span> </td>
                                            <td>
                                                <div class="img"></div>

                                                   <div> <p style="float: center;font-weight: bold;">
                                                        {% if w.product.in_stock %}
                                                            <span style="color: green;">In stock</span>
                                                        {% else %}
                                                            <span style="color: red;">Out of Stock</span>
                                                        {% endif %}
                                                    </p>
                                                </div>
                                                    
                                            </td>
                                            <td>
                                                <input type="hidden" value="1" name="" id="product-quantity" class="product-quantity-{{w.product.id}}" >
                                                <input type="hidden" value="{{w.product.pid}}" name="" id="" class="product-pid-{{w.product.id}}" >
                                                <input type="hidden" value="{{w.product.image.url}}" id="" class="product-image-{{w.product.id}}" >
                                                <input type="hidden" value="{{w.product.id}}" id="" class="product-id-{{w.product.id}}" >
                                                <input type="hidden" value="{{w.product.title}}" name="" id="" class="product-title-{{w.product.id}}" >

                                                <button  class="btn-cart add-to-cart-btn" data-index="{{w.product.id}}">Add to Cart</button>
                                            </td>
                                            <td>
                                                <button class="delete-wishlist-product" data-wishlist-product="{{ w.id }}"><i class="fa fa-trash"></i></button>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Wishlist End -->
        
        
        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>
        
        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/function.js' %}"></script>

    </body>
</html>